### ISSUE TITLE
Issues with the next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [schloerke/autocogs#11]
Hi

We are preparing a new ggplot2 release that include bug fixes which unfortunately breaks some code in autocogs. The issue we have detected revolves around autocogs calling `compute_aesthetics` before `setup_layer()` has been called, e.g. here: 

https://github.com/schloerke/autocogs/blob/3f87c44fdc08410d708bb3610aa5c5f5d44c7b33/R/layer_info.R#L40

We plan to submit ggplot2 on May 31st and hope you'll be able to submit a fix before that

**Comment by schloerke** [comment]
Fixed in 343e785 in #12
